import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Sora } from "next/font/google";
import "./globals.css";
import Header1 from "@/components/header1";
import Footer from "@/components/footer";
import Providers from "@/app/providers";
import Script from "next/script";
  
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
});

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
  weight: ["300", "400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "MVAntix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${sora.variable} antialiased`}
      >
        <Providers>
          <Header1/>
          {children}
            <Script id="zoho-salesiq-init" strategy="afterInteractive">
          {`
            window.$zoho=window.$zoho || {};
            $zoho.salesiq=$zoho.salesiq||{ready:function(){}};
          `}
        </Script>

        <Script
          id="zoho-salesiq-widget"
          src="https://salesiq.zohopublic.in/widget?wc=siqc64af953fda77f44847639357a51eb0b5135fdcd79266059e9fc918d5a991333"
          strategy="afterInteractive"
        />
          <Script id="zsiqchat" strategy="afterInteractive">
  {`
    var $zoho = window.$zoho || {};
    $zoho.salesiq = $zoho.salesiq || {
      widgetcode: "siqc64af953fda77f44847639357a51eb0b5135fdcd79266059e9fc918d5a991333",
      values: {},
      ready: function(){}
    };
    var d = document;
    var s = d.createElement("script");
    s.type = "text/javascript";
    s.id = "zsiqscript";
    s.defer = true;
    s.src = "https://salesiq.zoho.in/widget";
    var t = d.getElementsByTagName("script")[0];
    t.parentNode.insertBefore(s, t);
  `}
</Script>
        
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
